DATASET_PATH = "./data/dataset/"
POSSIBLE_ANSWER_PATH = "./data/possible_answer/"
API_STATUS_CHECK_DATA_PATH = "./data/api_status_check_data/"
RESULT_FILE_DIR = "./result/"
SCORE_FILE_DIR = "./score/"